<?php namespace Anomaly\Streams\Platform\Model\Users;

use Anomaly\Streams\Platform\Entry\EntryModel;

class UsersUsersEntryModel extends EntryModel
{

    use \Illuminate\Database\Eloquent\SoftDeletes;

    protected $searchable = true;

    protected $table = 'users_users';

    protected $titleName = 'display_name';

    protected $rules = [
'email' => 'required|unique:users_users,email',
'username' => 'required|unique:users_users,username',
'password' => 'required',
'roles' => 'required',
'display_name' => 'required',
'first_name' => '',
'last_name' => '',
'activated' => '',
'enabled' => '',
'permissions' => '',
'last_login_at' => '',
'remember_token' => '',
'activation_code' => '',
'reset_code' => '',
'last_activity_at' => '',
'ip_address' => '',
];

    protected $fields = [
'email',
'username',
'password',
'roles',
'display_name',
'first_name',
'last_name',
'activated',
'enabled',
'permissions',
'last_login_at',
'remember_token',
'activation_code',
'reset_code',
'last_activity_at',
'ip_address',
];

    protected $dates = ['created_at', 'updated_at', 'last_login_at', 'last_activity_at', 'deleted_at'];

    protected $relationships = ['roles'];

    

    

    

    protected $stream = [
'id' => '32',
'namespace' => 'users',
'slug' => 'users',
'prefix' => 'users_',
'title_column' => 'display_name',
'order_by' => 'id',
'locked' => '0',
'hidden' => '0',
'sortable' => '0',
'searchable' => '1',
'trashable' => '1',
'translatable' => '0',
'config' => 'a:0:{}',
'assignments' => [
[
'id' => 195,
'sort_order' => 99,
'stream_id' => 32,
'field_id' => 175,
'config' => 'a:0:{}',
'unique' => 1,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '175',
'namespace' => 'users',
'slug' => 'email',
'type' => 'anomaly.field_type.email',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 175,
'field_id' => 175,
'locale' => 'en',
'name' => 'anomaly.module.users::field.email.name',
'placeholder' => 'anomaly.module.users::field.email.placeholder',
'warning' => 'anomaly.module.users::field.email.warning',
'instructions' => 'anomaly.module.users::field.email.instructions',
],
],
],
'translations' => [
[
'id' => 195,
'assignment_id' => 195,
'locale' => 'en',
'label' => 'anomaly.module.users::field.email.label.users',
'warning' => 'anomaly.module.users::field.email.warning.users',
'placeholder' => 'anomaly.module.users::field.email.placeholder.users',
'instructions' => 'anomaly.module.users::field.email.instructions.users',
],
],
],
[
'id' => 196,
'sort_order' => 100,
'stream_id' => 32,
'field_id' => 176,
'config' => 'a:0:{}',
'unique' => 1,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '176',
'namespace' => 'users',
'slug' => 'username',
'type' => 'anomaly.field_type.slug',
'config' => 'a:2:{s:4:"type";s:1:"_";s:9:"lowercase";b:0;}',
'locked' => '1',
'translations' => [
[
'id' => 176,
'field_id' => 176,
'locale' => 'en',
'name' => 'anomaly.module.users::field.username.name',
'placeholder' => 'anomaly.module.users::field.username.placeholder',
'warning' => 'anomaly.module.users::field.username.warning',
'instructions' => 'anomaly.module.users::field.username.instructions',
],
],
],
'translations' => [
[
'id' => 196,
'assignment_id' => 196,
'locale' => 'en',
'label' => 'anomaly.module.users::field.username.label.users',
'warning' => 'anomaly.module.users::field.username.warning.users',
'placeholder' => 'anomaly.module.users::field.username.placeholder.users',
'instructions' => 'anomaly.module.users::field.username.instructions.users',
],
],
],
[
'id' => 197,
'sort_order' => 101,
'stream_id' => 32,
'field_id' => 177,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '177',
'namespace' => 'users',
'slug' => 'password',
'type' => 'anomaly.field_type.text',
'config' => 'a:1:{s:4:"type";s:8:"password";}',
'locked' => '1',
'translations' => [
[
'id' => 177,
'field_id' => 177,
'locale' => 'en',
'name' => 'anomaly.module.users::field.password.name',
'placeholder' => 'anomaly.module.users::field.password.placeholder',
'warning' => 'anomaly.module.users::field.password.warning',
'instructions' => 'anomaly.module.users::field.password.instructions',
],
],
],
'translations' => [
[
'id' => 197,
'assignment_id' => 197,
'locale' => 'en',
'label' => 'anomaly.module.users::field.password.label.users',
'warning' => 'anomaly.module.users::field.password.warning.users',
'placeholder' => 'anomaly.module.users::field.password.placeholder.users',
'instructions' => 'anomaly.module.users::field.password.instructions.users',
],
],
],
[
'id' => 198,
'sort_order' => 102,
'stream_id' => 32,
'field_id' => 195,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '195',
'namespace' => 'users',
'slug' => 'roles',
'type' => 'anomaly.field_type.multiple',
'config' => 'a:1:{s:7:"related";s:34:"Anomaly\UsersModule\Role\RoleModel";}',
'locked' => '1',
'translations' => [
[
'id' => 195,
'field_id' => 195,
'locale' => 'en',
'name' => 'anomaly.module.users::field.roles.name',
'placeholder' => 'anomaly.module.users::field.roles.placeholder',
'warning' => 'anomaly.module.users::field.roles.warning',
'instructions' => 'anomaly.module.users::field.roles.instructions',
],
],
],
'translations' => [
[
'id' => 198,
'assignment_id' => 198,
'locale' => 'en',
'label' => 'anomaly.module.users::field.roles.label.users',
'warning' => 'anomaly.module.users::field.roles.warning.users',
'placeholder' => 'anomaly.module.users::field.roles.placeholder.users',
'instructions' => 'anomaly.module.users::field.roles.instructions.users',
],
],
],
[
'id' => 199,
'sort_order' => 103,
'stream_id' => 32,
'field_id' => 183,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '183',
'namespace' => 'users',
'slug' => 'display_name',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 183,
'field_id' => 183,
'locale' => 'en',
'name' => 'anomaly.module.users::field.display_name.name',
'placeholder' => 'anomaly.module.users::field.display_name.placeholder',
'warning' => 'anomaly.module.users::field.display_name.warning',
'instructions' => 'anomaly.module.users::field.display_name.instructions',
],
],
],
'translations' => [
[
'id' => 199,
'assignment_id' => 199,
'locale' => 'en',
'label' => 'anomaly.module.users::field.display_name.label.users',
'warning' => 'anomaly.module.users::field.display_name.warning.users',
'placeholder' => 'anomaly.module.users::field.display_name.placeholder.users',
'instructions' => 'anomaly.module.users::field.display_name.instructions.users',
],
],
],
[
'id' => 200,
'sort_order' => 104,
'stream_id' => 32,
'field_id' => 184,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'translatable' => 0,
'field' => [
'id' => '184',
'namespace' => 'users',
'slug' => 'first_name',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 184,
'field_id' => 184,
'locale' => 'en',
'name' => 'anomaly.module.users::field.first_name.name',
'placeholder' => 'anomaly.module.users::field.first_name.placeholder',
'warning' => 'anomaly.module.users::field.first_name.warning',
'instructions' => 'anomaly.module.users::field.first_name.instructions',
],
],
],
'translations' => [
[
'id' => 200,
'assignment_id' => 200,
'locale' => 'en',
'label' => 'anomaly.module.users::field.first_name.label.users',
'warning' => 'anomaly.module.users::field.first_name.warning.users',
'placeholder' => 'anomaly.module.users::field.first_name.placeholder.users',
'instructions' => 'anomaly.module.users::field.first_name.instructions.users',
],
],
],
[
'id' => 201,
'sort_order' => 105,
'stream_id' => 32,
'field_id' => 185,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'translatable' => 0,
'field' => [
'id' => '185',
'namespace' => 'users',
'slug' => 'last_name',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 185,
'field_id' => 185,
'locale' => 'en',
'name' => 'anomaly.module.users::field.last_name.name',
'placeholder' => 'anomaly.module.users::field.last_name.placeholder',
'warning' => 'anomaly.module.users::field.last_name.warning',
'instructions' => 'anomaly.module.users::field.last_name.instructions',
],
],
],
'translations' => [
[
'id' => 201,
'assignment_id' => 201,
'locale' => 'en',
'label' => 'anomaly.module.users::field.last_name.label.users',
'warning' => 'anomaly.module.users::field.last_name.warning.users',
'placeholder' => 'anomaly.module.users::field.last_name.placeholder.users',
'instructions' => 'anomaly.module.users::field.last_name.instructions.users',
],
],
],
[
'id' => 202,
'sort_order' => 106,
'stream_id' => 32,
'field_id' => 192,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'translatable' => 0,
'field' => [
'id' => '192',
'namespace' => 'users',
'slug' => 'activated',
'type' => 'anomaly.field_type.boolean',
'config' => 'a:1:{s:13:"default_value";b:0;}',
'locked' => '1',
'translations' => [
[
'id' => 192,
'field_id' => 192,
'locale' => 'en',
'name' => 'anomaly.module.users::field.activated.name',
'placeholder' => 'anomaly.module.users::field.activated.placeholder',
'warning' => 'anomaly.module.users::field.activated.warning',
'instructions' => 'anomaly.module.users::field.activated.instructions',
],
],
],
'translations' => [
[
'id' => 202,
'assignment_id' => 202,
'locale' => 'en',
'label' => 'anomaly.module.users::field.activated.label.users',
'warning' => 'anomaly.module.users::field.activated.warning.users',
'placeholder' => 'anomaly.module.users::field.activated.placeholder.users',
'instructions' => 'anomaly.module.users::field.activated.instructions.users',
],
],
],
[
'id' => 203,
'sort_order' => 107,
'stream_id' => 32,
'field_id' => 193,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'translatable' => 0,
'field' => [
'id' => '193',
'namespace' => 'users',
'slug' => 'enabled',
'type' => 'anomaly.field_type.boolean',
'config' => 'a:1:{s:13:"default_value";b:1;}',
'locked' => '1',
'translations' => [
[
'id' => 193,
'field_id' => 193,
'locale' => 'en',
'name' => 'anomaly.module.users::field.enabled.name',
'placeholder' => 'anomaly.module.users::field.enabled.placeholder',
'warning' => 'anomaly.module.users::field.enabled.warning',
'instructions' => 'anomaly.module.users::field.enabled.instructions',
],
],
],
'translations' => [
[
'id' => 203,
'assignment_id' => 203,
'locale' => 'en',
'label' => 'anomaly.module.users::field.enabled.label.users',
'warning' => 'anomaly.module.users::field.enabled.warning.users',
'placeholder' => 'anomaly.module.users::field.enabled.placeholder.users',
'instructions' => 'anomaly.module.users::field.enabled.instructions.users',
],
],
],
[
'id' => 204,
'sort_order' => 108,
'stream_id' => 32,
'field_id' => 182,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'translatable' => 0,
'field' => [
'id' => '182',
'namespace' => 'users',
'slug' => 'permissions',
'type' => 'anomaly.field_type.checkboxes',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 182,
'field_id' => 182,
'locale' => 'en',
'name' => 'anomaly.module.users::field.permissions.name',
'placeholder' => 'anomaly.module.users::field.permissions.placeholder',
'warning' => 'anomaly.module.users::field.permissions.warning',
'instructions' => 'anomaly.module.users::field.permissions.instructions',
],
],
],
'translations' => [
[
'id' => 204,
'assignment_id' => 204,
'locale' => 'en',
'label' => 'anomaly.module.users::field.permissions.label.users',
'warning' => 'anomaly.module.users::field.permissions.warning.users',
'placeholder' => 'anomaly.module.users::field.permissions.placeholder.users',
'instructions' => 'anomaly.module.users::field.permissions.instructions.users',
],
],
],
[
'id' => 205,
'sort_order' => 109,
'stream_id' => 32,
'field_id' => 180,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'translatable' => 0,
'field' => [
'id' => '180',
'namespace' => 'users',
'slug' => 'last_login_at',
'type' => 'anomaly.field_type.datetime',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 180,
'field_id' => 180,
'locale' => 'en',
'name' => 'anomaly.module.users::field.last_login_at.name',
'placeholder' => 'anomaly.module.users::field.last_login_at.placeholder',
'warning' => 'anomaly.module.users::field.last_login_at.warning',
'instructions' => 'anomaly.module.users::field.last_login_at.instructions',
],
],
],
'translations' => [
[
'id' => 205,
'assignment_id' => 205,
'locale' => 'en',
'label' => 'anomaly.module.users::field.last_login_at.label.users',
'warning' => 'anomaly.module.users::field.last_login_at.warning.users',
'placeholder' => 'anomaly.module.users::field.last_login_at.placeholder.users',
'instructions' => 'anomaly.module.users::field.last_login_at.instructions.users',
],
],
],
[
'id' => 206,
'sort_order' => 110,
'stream_id' => 32,
'field_id' => 178,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'translatable' => 0,
'field' => [
'id' => '178',
'namespace' => 'users',
'slug' => 'remember_token',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 178,
'field_id' => 178,
'locale' => 'en',
'name' => 'anomaly.module.users::field.remember_token.name',
'placeholder' => 'anomaly.module.users::field.remember_token.placeholder',
'warning' => 'anomaly.module.users::field.remember_token.warning',
'instructions' => 'anomaly.module.users::field.remember_token.instructions',
],
],
],
'translations' => [
[
'id' => 206,
'assignment_id' => 206,
'locale' => 'en',
'label' => 'anomaly.module.users::field.remember_token.label.users',
'warning' => 'anomaly.module.users::field.remember_token.warning.users',
'placeholder' => 'anomaly.module.users::field.remember_token.placeholder.users',
'instructions' => 'anomaly.module.users::field.remember_token.instructions.users',
],
],
],
[
'id' => 207,
'sort_order' => 111,
'stream_id' => 32,
'field_id' => 190,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'translatable' => 0,
'field' => [
'id' => '190',
'namespace' => 'users',
'slug' => 'activation_code',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 190,
'field_id' => 190,
'locale' => 'en',
'name' => 'anomaly.module.users::field.activation_code.name',
'placeholder' => 'anomaly.module.users::field.activation_code.placeholder',
'warning' => 'anomaly.module.users::field.activation_code.warning',
'instructions' => 'anomaly.module.users::field.activation_code.instructions',
],
],
],
'translations' => [
[
'id' => 207,
'assignment_id' => 207,
'locale' => 'en',
'label' => 'anomaly.module.users::field.activation_code.label.users',
'warning' => 'anomaly.module.users::field.activation_code.warning.users',
'placeholder' => 'anomaly.module.users::field.activation_code.placeholder.users',
'instructions' => 'anomaly.module.users::field.activation_code.instructions.users',
],
],
],
[
'id' => 208,
'sort_order' => 112,
'stream_id' => 32,
'field_id' => 188,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'translatable' => 0,
'field' => [
'id' => '188',
'namespace' => 'users',
'slug' => 'reset_code',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 188,
'field_id' => 188,
'locale' => 'en',
'name' => 'anomaly.module.users::field.reset_code.name',
'placeholder' => 'anomaly.module.users::field.reset_code.placeholder',
'warning' => 'anomaly.module.users::field.reset_code.warning',
'instructions' => 'anomaly.module.users::field.reset_code.instructions',
],
],
],
'translations' => [
[
'id' => 208,
'assignment_id' => 208,
'locale' => 'en',
'label' => 'anomaly.module.users::field.reset_code.label.users',
'warning' => 'anomaly.module.users::field.reset_code.warning.users',
'placeholder' => 'anomaly.module.users::field.reset_code.placeholder.users',
'instructions' => 'anomaly.module.users::field.reset_code.instructions.users',
],
],
],
[
'id' => 209,
'sort_order' => 113,
'stream_id' => 32,
'field_id' => 181,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'translatable' => 0,
'field' => [
'id' => '181',
'namespace' => 'users',
'slug' => 'last_activity_at',
'type' => 'anomaly.field_type.datetime',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 181,
'field_id' => 181,
'locale' => 'en',
'name' => 'anomaly.module.users::field.last_activity_at.name',
'placeholder' => 'anomaly.module.users::field.last_activity_at.placeholder',
'warning' => 'anomaly.module.users::field.last_activity_at.warning',
'instructions' => 'anomaly.module.users::field.last_activity_at.instructions',
],
],
],
'translations' => [
[
'id' => 209,
'assignment_id' => 209,
'locale' => 'en',
'label' => 'anomaly.module.users::field.last_activity_at.label.users',
'warning' => 'anomaly.module.users::field.last_activity_at.warning.users',
'placeholder' => 'anomaly.module.users::field.last_activity_at.placeholder.users',
'instructions' => 'anomaly.module.users::field.last_activity_at.instructions.users',
],
],
],
[
'id' => 210,
'sort_order' => 114,
'stream_id' => 32,
'field_id' => 179,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'translatable' => 0,
'field' => [
'id' => '179',
'namespace' => 'users',
'slug' => 'ip_address',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 179,
'field_id' => 179,
'locale' => 'en',
'name' => 'anomaly.module.users::field.ip_address.name',
'placeholder' => 'anomaly.module.users::field.ip_address.placeholder',
'warning' => 'anomaly.module.users::field.ip_address.warning',
'instructions' => 'anomaly.module.users::field.ip_address.instructions',
],
],
],
'translations' => [
[
'id' => 210,
'assignment_id' => 210,
'locale' => 'en',
'label' => 'anomaly.module.users::field.ip_address.label.users',
'warning' => 'anomaly.module.users::field.ip_address.warning.users',
'placeholder' => 'anomaly.module.users::field.ip_address.placeholder.users',
'instructions' => 'anomaly.module.users::field.ip_address.instructions.users',
],
],
],
],
'translations' => [
[
'id' => 32,
'stream_id' => 32,
'locale' => 'en',
'name' => 'anomaly.module.users::stream.users.name',
'description' => 'anomaly.module.users::stream.users.description',
],
],
];

    
public function roles()
{

return $this->getFieldType('roles')->getRelation();
}

}
